//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscountProduct.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public int IDUnit { get; set; }
        public decimal Count { get; set; }
        public int IDDiscount { get; set; }
        public string Manufacturer { get; set; }
        public string Supplier { get; set; }
        public int IDProductCategory { get; set; }
        public int QuantitiInStock { get; set; }
        public string Description { get; set; }
    
        public virtual CategoryProduct CategoryProduct { get; set; }
        public virtual DiscountDate DiscountDate { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
